version: "3"
services:
  guacamole:
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
    volumes:
      - ./config_data:/config
    ports:
      - 8080:8080

volumes:
  postgres:
    driver: local
