version: "3"
services:
  init-guacamole-db:
    image: guacamole/guacamole:latest
    command:
      [
        "/bin/sh",
        "-c",
        "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql",
      ]
    volumes:
      - dbinit:/init
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - dbinit:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - init-guacamole-db
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  guac:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - postgres
      - guacd
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  dbinit:
    driver: local
  dbdata:
    driver: local
